In [2]:
import numpy as np

## some basic things

In [19]:
array = np.array(5)
array = np.arange(12)
print("here is your array:",array)
print("reshaped array:",array.reshape(4,3))
array = np.arange(12).reshape(4,3)
print("array shape:",array.shape)
print("array dimensions:",array.ndim)
print("array data size:",array.size)

here is your array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
reshaped array: [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
array shape: (4, 3)
array dimensions: 2
array data size: 12


In [ ]:
ones = np.ones((3,4))
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [32]:
array1 = np.array([1,2,3,4])
array2 = np.arange(5,9)
new_array = array1 * array2
new_array

array([ 5, 12, 21, 32])

In [34]:
new_array > 10

array([False,  True,  True,  True])

### For creating random value we can use `randn`

In [3]:
np.random.randn(6,4)

array([[-0.6276004 ,  0.60795536, -1.04896033,  0.56021964],
       [ 1.25694752, -0.11037863, -0.25844127,  0.46595882],
       [-0.3370426 ,  0.04148065, -0.49912248,  0.74264415],
       [-1.29263757, -0.99284669,  0.98825057, -0.16154207],
       [-0.99994603, -1.34151058, -1.01780383, -0.49441478],
       [-1.86861937, -0.42474128, -1.01424295,  0.05200427]])

Which the argvs are the shape of the outpu